int SIDES = 4;
int STROKE_WIDTH=3;
int STROKE_COLOR=56;
int SATURATION=100;
int BRIGHTNESS=100;
int FUNCTION_SELECTED=0;
int CLICKED_MOUSE_X=0;
int CLICKED_MOUSE_Y=0;
int SKETCH_WIDTH = 800;
int SKETCH_HEIGHT = 680;
BresenUI UI;
BresenForm SELECTION_RECT = null;
BresenForm SELECTED_FORM = null;
ArrayList<BresenForm> forms= new ArrayList<BresenForm>();